apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: mlops-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22, pipelines.kubeflow.org/pipeline_compilation_time: '2025-06-27T23:37:16.151844',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "This is my first ever
      kubeflow pipeline", "name": "MLOPS Pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22}
spec:
  entrypoint: mlops-pipeline
  templates:
  - name: data-ingestion
    container:
      command: [python, src/data_ingestion.py]
      env:
      - {name: GOOGLE_APPLICATION_CREDENTIALS, value: /app/credentials/credentials.json}
      image: eduardosousa1493/my-mlops-app:latest
      volumeMounts:
      - {mountPath: /app/credentials, name: gcp-sa-key, readOnly: true}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    initContainers:
    - command: [sh, -c, "echo \"Init container substitu\xEDdo com sucesso\""]
      image: busybox:1.36.1
      name: kfp-replacement-init-container
    volumes:
    - name: gcp-sa-key
      secret: {secretName: gcp-sa-key}
  - name: data-processing
    container:
      command: [python, src/data_processing.py]
      image: eduardosousa1493/my-mlops-app:latest
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    initContainers:
    - command: [sh, -c, "echo \"Init container substitu\xEDdo com sucesso\""]
      image: busybox:1.36.1
      name: kfp-replacement-init-container
  - name: mlops-pipeline
    dag:
      tasks:
      - {name: data-ingestion, template: data-ingestion}
      - name: data-processing
        template: data-processing
        dependencies: [data-ingestion]
      - name: model-training
        template: model-training
        dependencies: [data-processing]
  - name: model-training
    container:
      command: [python, src/model_training.py]
      image: eduardosousa1493/my-mlops-app:latest
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
    initContainers:
    - command: [sh, -c, "echo \"Init container substitu\xEDdo com sucesso\""]
      image: busybox:1.36.1
      name: kfp-replacement-init-container
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
